spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #page size default 값 변경
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true #1부터 시작하는 index parameter
        #그런데 페이지 뒤의 정보들이 맞지 않는 한계가 있다

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql : true
        format_sql: true
logging:
  level:
    org.hibernate.SQL : debug #console이 아니라 로그로 남김
    #org.hibernate.type : trace #파라미터까지 볼 수 있다
